// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import "package:firebase_core/firebase_core.dart" show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDcZJvJ1-mtPIYuhX7jXh8ruFxN9x3Fb4',
    appId: '1:315687502301:web:d5b8d0fdabb3bcdb31b634',
    messagingSenderId: '315687502301',
    projectId: 'crudflutter-78e59',
    authDomain: 'crudflutter-78e59.firebaseapp.com',
    storageBucket: 'crudflutter-78e59.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2NPMZD66ARoGgjUSlezUHjhy4sJ15z2k',
    appId: '1:315687502301:android:5e5c3422a3f73e2631b634',
    messagingSenderId: '315687502301',
    projectId: 'crudflutter-78e59',
    storageBucket: 'crudflutter-78e59.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDcZJvJ1-mtPIYuhX7jXh8ruFxN9x3Fb4',
    appId: '1:315687502301:web:5bbdc27fc82c92d231b634',
    messagingSenderId: '315687502301',
    projectId: 'crudflutter-78e59',
    authDomain: 'crudflutter-78e59.firebaseapp.com',
    storageBucket: 'crudflutter-78e59.appspot.com',
  );
}
